# Generated by Django 6.0.2 on 2026-04-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddrop.hopital'),
        ),
        migrations.AlterField(
            model_name='demandeurgente',
            name='hopital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddrop.hopital'),
        ),
        migrations.AlterField(
            model_name='don',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddrop.donneur'),
        ),
        migrations.AlterField(
            model_name='don',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reddrop.hopital'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddrop.demandeurgente'),
        ),
        migrations.AlterField(
            model_name='reponseappel',
            name='donneur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddrop.donneur'),
        ),
    ]
