# Generated by Django 5.2.11 on 2026-04-19 10:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddrop', '0002_alter_campagne_hopital_alter_demandeurgente_hopital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donneur_banque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hopital',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hopital_banque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, help_text="Lien optionnel vers l'action", max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('statut', models.CharField(choices=[('P', 'Planifié'), ('H', 'Honoré'), ('A', 'Annulé')], default='P', max_length=1)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reddrop.campagne')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='reddrop.donneur')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='reddrop.hopital')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='StockSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('type_produit', models.CharField(choices=[('GR', 'Globules Rouges'), ('PL', 'Plaquettes'), ('PS', 'Plasma')], default='GR', max_length=2)),
                ('date_prelevement', models.DateField(default=datetime.date.today)),
                ('date_peremption', models.DateField(blank=True)),
                ('statut', models.CharField(choices=[('TEST', 'En test'), ('OK', 'En stock'), ('USED', 'Utilisé'), ('EXP', 'Expiré')], default='TEST', max_length=4)),
                ('don', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reddrop.don')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='reddrop.hopital')),
            ],
            options={
                'ordering': ['date_peremption'],
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('ATT', 'En attente'), ('APP', 'Approuvé'), ('REJ', 'Rejeté'), ('TER', 'Terminé')], default='ATT', max_length=3)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('hopital_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_demandes', to='reddrop.hopital')),
                ('hopital_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_fournis', to='reddrop.hopital')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
    ]
