# Generated by Django 5.2.11 on 2026-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellé', models.CharField(max_length=100)),
                ('discription', models.TextField(default='non définit')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
