# Generated by Django 5.2.11 on 2026-03-07 11:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dateCde',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('em', 'Emballé'), ('fr', 'Frais'), ('cs', 'Conserve')], default='em', max_length=2),
        ),
    ]
