# Generated by Django 5.2.11 on 2026-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_produit_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='email_contact',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
