# Generated by Django 6.0.2 on 2026-05-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_alter_commande_options_commande_date_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
