# Generated by Django 6.0.2 on 2026-05-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_produit_prix_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.CreateModel(
            name='ProduitFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_livraison_jours', models.PositiveIntegerField(default=3)),
                ('is_preferred', models.BooleanField(default=False)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='magasin.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='magasin.produit')),
            ],
            options={
                'verbose_name': "Source d'approvisionnement",
                'unique_together': {('produit', 'fournisseur')},
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='fournisseurs',
            field=models.ManyToManyField(related_name='produits_proposes', through='magasin.ProduitFournisseur', to='magasin.fournisseur'),
        ),
    ]
