# Generated by Django 5.2.11 on 2026-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_alter_categorie_options_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
