# Generated by Django 6.0.2 on 2026-05-06 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_commande_adresse_livraison_commande_email_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-dateCde', '-id'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='commande',
            name='date_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_expedition',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='note_admin',
            field=models.TextField(blank=True, verbose_name='Note interne admin'),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_suivi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numéro de suivi'),
        ),
        migrations.AddField(
            model_name='commande',
            name='raison_annulation',
            field=models.TextField(blank=True, verbose_name="Raison d'annulation"),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_minimum',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock minimum (alerte)'),
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé au fournisseur'), ('accepte', 'Accepté'), ('recu', 'Reçu en magasin'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Référence BDC')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_de_commande', to='magasin.commande', verbose_name='Commande client liée (optionnel)')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_de_commande', to='magasin.fournisseur')),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BonDeCommandeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='magasin.bondecommande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='magasin.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='magasin.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='magasin.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nouvelle_commande', 'Nouvelle commande'), ('statut_commande', 'Changement de statut'), ('stock_bas', 'Stock bas'), ('bdc_accepte', 'BDC accepté'), ('bdc_recu', 'BDC reçu'), ('commande_annulee', 'Commande annulée')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magasin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
